const QUESTIONS = [
  { text: 'Qual dessas dificuldades mais combina com você hoje?', opts: [
    {l:'A', t:'Estou começando e ainda preciso aprender o básico', p:0},
    {l:'B', t:'Sei alguns sinais, mas não consigo formar frases direito', p:1},
    {l:'C', t:'Consigo me comunicar um pouco, mas travo na estrutura da Libras', p:2},
    {l:'D', t:'Já sei Libras, mas tenho dificuldade para interpretar textos, vídeos ou falas', p:3},
    {l:'E', t:'Já interpreto, mas quero melhorar fluência, clareza e segurança profissional', p:4},
  ]},
  { text: 'Qual é seu principal objetivo com a Libras?', opts: [
    {l:'A', t:'Começar a aprender do zero', p:0},
    {l:'B', t:'Conversar melhor com pessoas surdas no dia a dia', p:1},
    {l:'C', t:'Usar Libras no trabalho, igreja, escola ou atendimento', p:2},
    {l:'D', t:'Melhorar minha sinalização e perder a insegurança', p:3},
    {l:'E', t:'Atuar ou evoluir como intérprete/tradutora de Libras', p:4},
  ]},
  { text: 'Quando você tenta sinalizar, o que mais acontece?', opts: [
    {l:'A', t:'Não sei nem por onde começar', p:0},
    {l:'B', t:'Lembro alguns sinais isolados, mas travo muito', p:1},
    {l:'C', t:'Me comunico, mas fico insegura e cometo muitos erros', p:2},
    {l:'D', t:'Me comunico, mas sinto que falta estrutura e naturalidade', p:3},
    {l:'E', t:'Me comunico bem, mas quero mais fluidez e precisão', p:4},
  ]},
  { text: 'Você consegue entender surdos sinalizando naturalmente?', opts: [
    {l:'A', t:'Quase nada', p:0},
    {l:'B', t:'Entendo sinais isolados', p:1},
    {l:'C', t:'Entendo quando a pessoa sinaliza devagar ou em contexto', p:2},
    {l:'D', t:'Entendo a maior parte, mas me perco quando acelera', p:3},
    {l:'E', t:'Entendo bem, mas quero melhorar minha resposta e interpretação', p:4},
  ]},
  { text: 'Como você pensa quando tenta montar uma frase em Libras?', opts: [
    {l:'A', t:'Ainda não consigo montar frases', p:0},
    {l:'B', t:'Penso palavra por palavra em português', p:1},
    {l:'C', t:'Troco palavras por sinais, mas a ordem fica errada', p:2},
    {l:'D', t:'Tento seguir a estrutura visual, mas ainda fico presa ao português', p:3},
    {l:'E', t:'Penso em imagem e contexto, mas quero mais precisão', p:4},
  ]},
  { text: 'Você já estudou Libras formalmente?', opts: [
    {l:'A', t:'Nunca estudei', p:0},
    {l:'B', t:'Vi vídeos e tutoriais soltos na internet', p:1},
    {l:'C', t:'Fiz curso básico', p:2},
    {l:'D', t:'Fiz curso intermediário, Letras Libras ou formação longa', p:3},
    {l:'E', t:'Estudo há anos ou tenho contato profissional com Libras', p:4},
  ]},
  { text: 'Você já precisou interpretar ou traduzir algo em Libras?', opts: [
    {l:'A', t:'Nunca', p:0},
    {l:'B', t:'Só frases muito simples', p:1},
    {l:'C', t:'Já tentei, mas fiquei muito insegura', p:2},
    {l:'D', t:'Já interpreto, mas sinto dificuldade na estrutura e organização', p:3},
    {l:'E', t:'Já interpreto com frequência e quero melhorar técnica e fluência', p:4},
  ]},
  { text: 'Como você se sente em relação à expressão facial e corporal na Libras?', opts: [
    {l:'A', t:'Ainda não sei usar, estou no início', p:0},
    {l:'B', t:'Sei que existe, mas não uso na prática', p:1},
    {l:'C', t:'Uso um pouco, mas com muita dúvida', p:2},
    {l:'D', t:'Uso, mas sinto que falta naturalidade', p:3},
    {l:'E', t:'Uso bem, mas quero refinar para um nível mais profissional', p:4},
  ]},
  { text: 'Você sente que seu problema é mais falta de sinais ou falta de estrutura?', opts: [
    {l:'A', t:'Falta de sinais básicos — ainda estou no começo', p:0},
    {l:'B', t:'Principalmente falta de vocabulário', p:1},
    {l:'C', t:'Um pouco dos dois', p:2},
    {l:'D', t:'Eu até sei sinais, mas não sei organizar direito', p:3},
    {l:'E', t:'Preciso melhorar estrutura, tradução, expressão e clareza', p:4},
  ]},
  { text: 'Com que frequência você pratica Libras?', opts: [
    {l:'A', t:'Nunca pratiquei', p:0},
    {l:'B', t:'Raramente, só quando preciso', p:1},
    {l:'C', t:'Às vezes, mas sem orientação', p:2},
    {l:'D', t:'Com regularidade, mas sinto que estagnei', p:3},
    {l:'E', t:'Com frequência, inclusive em contextos profissionais', p:4},
  ]},
  { text: 'Qual frase mais combina com você hoje?', opts: [
    {l:'A', t:'"Quero aprender Libras do zero, sem nenhuma base ainda."', p:0},
    {l:'B', t:'"Sei poucos sinais e quero criar uma base melhor."', p:1},
    {l:'C', t:'"Já sei algumas coisas, mas não consigo conversar com segurança."', p:2},
    {l:'D', t:'"Sei Libras, mas erro na estrutura e travo para me expressar com clareza."', p:3},
    {l:'E', t:'"Já tenho base, mas quero evoluir em fluência, interpretação e profissionalismo."', p:4},
  ]},
  { text: 'O que mais te impede de se comunicar em Libras com confiança hoje?', opts: [
    {l:'A', t:'Não ter aprendido ainda — estou começando', p:0},
    {l:'B', t:'Ter poucos sinais e vocabulário limitado', p:1},
    {l:'C', t:'Insegurança e medo de errar na hora de sinalizar', p:2},
    {l:'D', t:'Dificuldade de organizar o raciocínio antes de sinalizar', p:3},
    {l:'E', t:'Falta de refinamento, precisão e desenvoltura profissional', p:4},
  ]},
];
