const QUESTIONS = [
  {
    text: 'Qual é o seu maior desafio com Libras hoje?',
    opts: [
      {l:'A', t:'Não sei nada ainda — quero começar do zero', p:0},
      {l:'B', t:'Sei alguns sinais, mas não consigo formar frases', p:1},
      {l:'C', t:'Me comunico, mas com muita insegurança e erros', p:2},
      {l:'D', t:'Sei Libras, mas trava na estrutura e organização', p:3},
      {l:'E', t:'Já interpreto, mas quero mais fluência e precisão', p:4},
    ],
    micro: [
      'Entendo… você está no ponto de partida 🌱',
      'Isso é muito comum nessa fase…',
      'Esse é o ponto exato de transição 🔑',
      'Isso me diz muito sobre o seu momento 👀',
      'Você já está bem à frente da maioria 💪',
    ],
  },
  {
    text: 'Qual é o seu principal objetivo com a Libras?',
    opts: [
      {l:'A', t:'Aprender do zero para me comunicar com surdos', p:0},
      {l:'B', t:'Conversar melhor com surdos no dia a dia', p:1},
      {l:'C', t:'Usar no trabalho, escola, atendimento ou família', p:2},
      {l:'D', t:'Melhorar minha sinalização e perder a insegurança', p:3},
      {l:'E', t:'Atuar ou evoluir como intérprete ou tradutora', p:4},
    ],
    micro: [
      'Anotei isso…',
      'Que objetivo lindo 😊',
      'Isso tem um impacto real na vida de outras pessoas…',
      'Segurança é tudo na comunicação 💪',
      'Isso muda tudo no seu diagnóstico 💜',
    ],
  },
  {
    text: 'Quando você tenta sinalizar uma frase, o que mais acontece?',
    opts: [
      {l:'A', t:'Não sei nem por onde começar', p:0},
      {l:'B', t:'Lembro sinais isolados, mas trava na hora de usar', p:1},
      {l:'C', t:'Consigo falar, mas com muita hesitação', p:2},
      {l:'D', t:'Consigo, mas a estrutura fica parecendo português sinalizado', p:3},
      {l:'E', t:'Me comunico bem, mas quero mais fluidez e naturalidade', p:4},
    ],
    micro: [
      'Isso vai mudar com o caminho certo…',
      'Travar é muito diferente de não saber 😊',
      'Isso faz muito sentido para o seu momento…',
      'Você está descrevendo algo muito específico e importante…',
      'Você já tem muito — só falta estruturar isso 💪',
    ],
    depositoEmocional: true,
  },
  {
    text: 'Você consegue entender surdos sinalizando naturalmente?',
    opts: [
      {l:'A', t:'Quase nada', p:0},
      {l:'B', t:'Entendo sinais isolados', p:1},
      {l:'C', t:'Entendo quando a pessoa sinaliza devagar', p:2},
      {l:'D', t:'Entendo bastante, mas me perco quando acelera', p:3},
      {l:'E', t:'Entendo bem, mas quero melhorar minha interpretação', p:4},
    ],
    micro: [
      'Isso é um ponto chave…',
      'Já é um começo importante!',
      'Isso é muito honesto 😊',
      'Você está mais avançad(a) do que imagina…',
      'Impressionante 👏',
    ],
  },
  {
    text: 'Como você se sente na hora de sinalizar?',
    opts: [
      {l:'A', t:'Perdido(a) — não sei nem por onde começar', p:0},
      {l:'B', t:'Travado(a) — conheço sinais mas não saem na hora', p:1},
      {l:'C', t:'Inseguro(a) — faço, mas com muita dúvida', p:2},
      {l:'D', t:'Sei sinalizar, mas sinto que falta organização e estrutura', p:3},
      {l:'E', t:'Quero refinamento e direcionamento individualizado', p:4},
    ],
    micro: [
      'Isso vai mudar em breve…',
      'Sentir isso é normal — e tem solução 😊',
      'Isso faz todo sentido…',
      'Você está tão mais perto do que imagina…',
      'Você já tem o que precisa — só falta a direção certa 💪',
    ],
  },
  {
    text: 'Qual é o seu histórico com o estudo de Libras?',
    opts: [
      {l:'A', t:'Nunca estudei formalmente', p:0},
      {l:'B', t:'Vi vídeos e tutoriais na internet', p:1},
      {l:'C', t:'Fiz um curso básico', p:2},
      {l:'D', t:'Fiz curso intermediário, Letras Libras ou formação longa', p:3},
      {l:'E', t:'Estudo há anos ou atuo profissionalmente com Libras', p:4},
    ],
    micro: [
      'Isso me ajuda muito a entender seu ponto de partida…',
      'Interessante… isso diz muito sobre como você aprende 👀',
      'Ótimo, isso me dá um contexto importante…',
      'Você já tem uma base bem sólida então…',
      'Agora estou entendendo muito melhor seu perfil…',
    ],
  },
  {
    text: 'Qual frase mais combina com você hoje?',
    opts: [
      {l:'A', t:'"Quero aprender Libras do jeito certo, do zero."', p:0},
      {l:'B', t:'"Sei pouco e quero criar uma base melhor."', p:1},
      {l:'C', t:'"Já sei algumas coisas, mas não consigo conversar com segurança."', p:2},
      {l:'D', t:'"Sei Libras, mas erro na estrutura e trava na hora de me expressar."', p:3},
      {l:'E', t:'"Já tenho base, mas quero fluência, processo tradutório e clareza profissional."', p:4},
    ],
    micro: [
      'Perfeito… isso confirma o que vi até aqui 👀',
      'Entendi — isso encaixa exatamente no que percebi…',
      'Muito preciso 🎯',
      'Isso é muito importante para o diagnóstico…',
      'Isso é exatamente o que precisava saber 💜',
    ],
  },
];
